_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  # WEIGHTS: detectron2://ImageNetPretrained/MSRA/R-50.pkl
  WEIGHTS: '/data2/users/abanerjee/doc_mask_lmp/model_final.pth'
  MASK_ON: True
  RESNETS:
    DEPTH: 101
DATASETS:
  TRAIN: ("doclaynet_train",)
  TEST: ("doclaynet_val",)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.0025
  STEPS: (210000, 250000)
  MAX_ITER: 270000
TEST:
  EVAL_PERIOD: 2000
# OUTPUT_DIR: "output/doclaynet/mask_rcnn/rn50"