_BASE_: "../Base-RCNN-ViT.yaml"
MODEL:
  PIXEL_MEAN: [ 127.5, 127.5, 127.5 ]
  PIXEL_STD: [ 127.5, 127.5, 127.5 ]
  WEIGHTS: "./pretrained/ViTt_Imagenet22k1k_timm_detectron2.pth"
  VIT:
    ARCH: "vit_tiny_patch16_224"
    OUT_FEATURES: ["layer3", "layer5", "layer7", "layer11"]
    IMG_SIZE: (384, 384)
  ROI_HEADS:
    NUM_CLASSES: 11
DATASETS:
  TRAIN: ("doclaynet_train",)
  TEST: ("doclaynet_val",)
SOLVER:
  WARMUP_ITERS: 1000
  IMS_PER_BATCH: 16
  # MAX_ITER: 60000
  STEPS: (210000, 250000)
  MAX_ITER: 300000
  CHECKPOINT_PERIOD: 2000
INPUT:
  CROP:
    ENABLED: False
    TYPE: "absolute_range"
    SIZE: (384, 384)
  MIN_SIZE_TRAIN: (384,) # (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 384
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 2000
OUTPUT_DIR: './output/teacher/vitt_imagenet_doclaynet_tecaher/'