_BASE_: "../Base-RCNN-DiT.yaml"
MODEL:
  PIXEL_MEAN: [ 127.5, 127.5, 127.5 ]
  PIXEL_STD: [ 127.5, 127.5, 127.5 ]
  WEIGHTS: "https://layoutlm.blob.core.windows.net/dit/dit-pts/dit-base-224-p16-500k-62d53a.pth"
  VIT:
    ARCH: "dit_base_patch16"
    OUT_FEATURES: ["layer3", "layer5", "layer7", "layer11"]
DATASETS:
  TRAIN: ("doclaynet_train",)
  TEST: ("doclaynet_val",)
SOLVER:
  WARMUP_ITERS: 1000
  IMS_PER_BATCH: 16
  # MAX_ITER: 60000
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  CHECKPOINT_PERIOD: 2000
TEST:
  EVAL_PERIOD: 2000
# OUTPUT_DIR: ''